name: densys-env
channels:
  - menpo
  - conda-forge
  - conda-forge/label/broken
  - default
dependencies:
  - python=3.5
  - alabaster
  - caffe
  - curl
  - flask
  - matplotlib
  - mock
  - numpy
  - numpy-base
  - opencv
  - pandas
  - pytest
  - python
  - scikit-image
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib
  - sphinxcontrib-websupport
  - twine
  - wheel
  - yaml
  - dlib

